// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtzib-1sThjH5B_NoPTiwtTgO1rhYjeB0',
    appId: '1:124809569219:web:5b54b5ccd44191e6819376',
    messagingSenderId: '124809569219',
    projectId: 'marbot-cec3f',
    authDomain: 'marbot-cec3f-dc827.firebaseapp.com',
    databaseURL: 'https://marbot-cec3f-default-rtdb.firebaseio.com',
    storageBucket: 'marbot-cec3f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9yo8Bvvs2mBkEDBWdySG_dpWRFo2s_rU',
    appId: '1:124809569219:android:c9cd786e5a6e3cd7819376',
    messagingSenderId: '124809569219',
    projectId: 'marbot-cec3f',
    databaseURL: 'https://marbot-cec3f-default-rtdb.firebaseio.com',
    storageBucket: 'marbot-cec3f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlnVH3rZaxa70MIbb7r8sIeLVO3ZtuOOs',
    appId: '1:124809569219:ios:562ec2a1eb9693a3819376',
    messagingSenderId: '124809569219',
    projectId: 'marbot-cec3f',
    databaseURL: 'https://marbot-cec3f-default-rtdb.firebaseio.com',
    storageBucket: 'marbot-cec3f.appspot.com',
    iosBundleId: 'com.example.marbot2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlnVH3rZaxa70MIbb7r8sIeLVO3ZtuOOs',
    appId: '1:124809569219:ios:d54d5eaae5a0657c819376',
    messagingSenderId: '124809569219',
    projectId: 'marbot-cec3f',
    databaseURL: 'https://marbot-cec3f-default-rtdb.firebaseio.com',
    storageBucket: 'marbot-cec3f.appspot.com',
    iosBundleId: 'com.example.marbot2.RunnerTests',
  );
}
