// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Reemplazar con los datos de tu nuevo proyecto Firebase
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'TU_WEB_API_KEY_AQUI',
    appId: 'TU_WEB_APP_ID_AQUI',
    messagingSenderId: 'TU_MESSAGING_SENDER_ID_AQUI',
    projectId: 'TU_NUEVO_PROJECT_ID_AQUI',
    authDomain: 'TU_NUEVO_PROJECT_ID_AQUI.firebaseapp.com',
    databaseURL: 'https://TU_NUEVO_PROJECT_ID_AQUI-default-rtdb.firebaseio.com',
    storageBucket: 'TU_NUEVO_PROJECT_ID_AQUI.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4Vh7fiRTz3qXMXnnGKtNo8mIbE_594vQ',
    appId: '1:8882501036:android:40a2bac5b68ae9214c3609',
    messagingSenderId: '8882501036',
    projectId: 'control-de-dispositivos-da082',
    databaseURL: 'https://control-de-dispositivos-da082-default-rtdb.firebaseio.com',
    storageBucket: 'control-de-dispositivos-da082.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlnVH3rZaxa70MIbb7r8sIeLVO3ZtuOOs',
    appId: 'TU_IOS_APP_ID_AQUI',
    messagingSenderId: 'TU_MESSAGING_SENDER_ID_AQUI',
    projectId: 'TU_NUEVO_PROJECT_ID_AQUI',
    databaseURL: 'https://TU_NUEVO_PROJECT_ID_AQUI-default-rtdb.firebaseio.com',
    storageBucket: 'TU_NUEVO_PROJECT_ID_AQUI.appspot.com',
    iosBundleId: 'com.example.marbot2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'TU_IOS_API_KEY_AQUI',
    appId: 'TU_MACOS_APP_ID_AQUI',
    messagingSenderId: 'TU_MESSAGING_SENDER_ID_AQUI',
    projectId: 'TU_NUEVO_PROJECT_ID_AQUI',
    databaseURL: 'https://TU_NUEVO_PROJECT_ID_AQUI-default-rtdb.firebaseio.com',
    storageBucket: 'TU_NUEVO_PROJECT_ID_AQUI.appspot.com',
    iosBundleId: 'com.example.marbot2.RunnerTests',
  );
}
